name: Daily Data Scrape

on:
  schedule:
    - cron: '0 12 * * *'  

jobs:
  run-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl command
        run: curl https://nufoodfinder-prod.up.railway.app/api/scrapeDailyItems

