name: Daily Data Scrape

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6am UTC every day

jobs:
  run-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl command
        run: curl https://nufoodfinder-prod.up.railway.app/api/scrapeDailyItems

