name: Data Scrape

on:
  schedule:
    # Daily at 12 PM UTC
    - cron: '0 12 * * *'

jobs:
  run-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Determine day of the week
        id: day-of-week
        run: echo "DAY_OF_WEEK=$(date +'%u')" >> $GITHUB_ENV
      - name: Run daily item scraping
        run: |
          curl -X GET https://api.nufood.me/api/scrapeDailyItems \
          -H "X-Custom-Auth: ${{ secrets.CRON_AUTH_TOKEN }}" \
          -H "User-Agent: GitHub-Cron-Job"
      # Check if the day is Sunday if it is we need to scrape the new operating times data
      # day of week is index Monday (1) to Sunday (7)
      - name: Run operating times scraping (only on Sundays)
        if: ${{ env.DAY_OF_WEEK == '7' }}
        run: |
          curl -X GET https://api.nufood.me/api/scrapeOperatingTimes \
          -H "X-Custom-Auth: ${{ secrets.CRON_AUTH_TOKEN }}" \
          -H "User-Agent: GitHub-Cron-Job"
